version: '3.8'

services:
  db:
    image: postgres:15
    container_name: news_db_container
    restart: always
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  ml-service:
    build: ./backend/ml_service
    container_name: ml_service_container
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend/ml_service/best_model.weights.h5:/app/best_model.weights.h5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # порт для кода
      - "15672:15672" # порт для админки
    restart: always

  backend:
    build: ./backend/news-service
    container_name: java_backend_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      #- ml-service
      - redis
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/news_db
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      ML_SERVICE_URL: http://ml-service:5000/predict
      

  frontend:
    build: ./frontend
    container_name: react_frontend_container
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: always

volumes:
  postgres_data: